name: Build and Test

on:
  push:
    branches: [main]
    tags:
      - "v*" # Add this to trigger on version tags
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          profile: minimal

      - name: Build static binary
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          cargo build --release --target x86_64-unknown-linux-musl

      # - name: Build Docker image
      #   run: docker build -t craftcms .

      # - name: Test Docker container
      #   run: |
      #     docker run --rm craftcms init-db
      #     docker run -d -p 3030:3030 --name craftcms craftcms serve
      #     sleep 5
      #     curl -f http://localhost:3030 || exit 1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-musl/release/craftcms
          asset_name: craftcms
          asset_content_type: application/octet-stream
