name: Build and Release
on:
 push:
   branches: [main]
   tags: ["v*"]
 pull_request:
   branches: [main]

jobs:
 build:
   strategy:
     matrix:
       target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: Swatinem/rust-cache@v2
     - uses: actions-rs/toolchain@v1
       with:
         toolchain: stable
         target: ${{ matrix.target }}
         profile: minimal

     - name: Install musl-tools
       run: |
         sudo apt-get update
         sudo apt-get install -y musl-tools

     - name: Build
       run: cargo build --release --target ${{ matrix.target }}

     - name: Verify static
       run: ldd target/${{ matrix.target }}/release/craftcms | grep -q "statically linked"

     - name: Generate checksum
       run: sha256sum target/${{ matrix.target }}/release/craftcms > craftcms-${{ matrix.target }}.sha256

     - name: Release
       if: startsWith(github.ref, 'refs/tags/')
       uses: softprops/action-gh-release@v1
       with:
         files: |
           target/${{ matrix.target }}/release/craftcms
           craftcms-${{ matrix.target }}.sha256
       env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
